sonar.projectKey=mern-cicd
sonar.projectName=MERN CI/CD
sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.coverage.exclusions=**/tests/**,**/main.jsx,backend/src/server.js
sonar.sourceEncoding=UTF-8
